NONE: GitHub Actions Test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -19,27 +19,25 @@ jobs:
         with:
           node-version: '22'
 
-      - name: Clone LibreTranslate
+      - name: Clone & Run LibreTranslate
         run: |
           git clone https://github.com/LibreTranslate/LibreTranslate
           cd LibreTranslate
           chmod +x run.sh
-
-      - name: Run LibreTranslate
-        run: |
-          cd LibreTranslate
           ./run.sh &
 
       - name: Wait for LibreTranslate to be ready
         run: |
-          for i in {1..100}; do
-            if curl -s -X GET "http://localhost:5000/frontend/settings" -H "accept: application/json"; then
-              echo "LibreTranslate is ready"
-              break
-            fi
-            echo "Waiting for LibreTranslate..."
-            sleep 2
+          for i in {1..60}; do
+          if curl -s -X GET "http://localhost:5000/frontend/settings" -H "accept: application/json"; then
+           echo "LibreTranslate is ready"
+           exit 0
+          fi
+          echo "Waiting for LibreTranslate... ($i/100)"
+          sleep 10
           done
+          echo "ERROR: LibreTranslate did not start in time."
+          exit 1
 
       - name: Set execute permissions
         run: |
